### ISSUE TITLE
Max candidates values mismatch?

### ISSUE THREAD

**Issue by mmalenta** [AstroAccelerateOrg/astro-accelerate#140] opened 2019-01-23 13:56 UTC
**Issue Summary**
This happens across multiple branches in one form or another. Before the `analysis_GPU` is called, `max_peak_size = (size_t) ( ndms[dm_range]*t_processed[dm_range][t]/2 );`, then inside the `analysis_GPU`, a local variable `local_max_list_size = (DMs_per_cycle*nTimesamples)/4;`. I might be missing something, but it looks to me, the whole business of possibly processing DM in multiple batches, like we're expecting half as many candidates locally as we do globally. 

**Steps to Reproduce**

**Expected Outcome**
Both divided by either 2 or 4?

**Actual Outcome**

**Configuration**

**Notes**

**Comment by KAdamek** [comment] 2019-01-25 11:23
The candidate list in AstroAccelerate is bit convoluted but not much. The array which is allocated before analysis was intended to keep all candidates from given timechunk  and range. There is "peak_pos" variable which keeps track of current position and how many candidate we have so far. However this could be defacto inside analysis, because AstroAccelerate standalone outputs everything to disc. The division by two is arbitrary it is mainly there to manage memory requirements. Changing the maximum number of candidates in variable "max_peak_size" you can change number of candidates which would be transferred to the host. If the number of candidates is too low, some candidate will be lost.

The way analysis processes the output of de-dispersion depends on available memory. Based on available memory de-dispersion output is separated into sub-chunks. Analysis code aims not to loose any candidates therefore it allocates the arrays d_peak_list_* where it can store the worst case when using peakfinding algorithm for candidate selection. The peak finding algorithm uses 3x3 stencil to locate maximum therefore the maximum number of candidates is approximately (it is approximate because of border conditions)  local_max_list_size = (DMs_per_cycle*nTimesamples)/4, eg only every fourth point could be a peak. The candidates from this temporary array is then stored to the host arrays h_peak_list_* and then "peak_pos" is updated.

Hope this helps.

**Comment by mmalenta** [comment] 2019-01-25 12:07
That helps! Thank you for the explanation!

**Closed as completed** 2019-01-25 12:07 UTC
Labels: Question
