### ISSUE TITLE
Fix Wiki page about single pulse

### ISSUE THREAD

**Issue by KAdamek** [AstroAccelerateOrg/astro-accelerate#136] opened 2018-12-22 10:52 UTC
**Issue Summary**
There are missing figures in single pulse detection page on github wiki

**Steps to Reproduce**

**Expected Outcome**

**Actual Outcome**

**Configuration**

**Notes**

**Comment by ccarels** [comment] 2019-01-03 11:50
@KAdamek These are missing references to images that were previously stored in the repository. There is also a missing image on the "Calculation of mean and standard deviation in AA" page. The other images on the GitHub wiki page look like they are hosted on the OeRC. Can we store all images on the OeRC? That way they don't have to bloat the repository size. Assigning back to you because I don't have access to upload images to the OeRC.

**Comment by ccarels** [comment] 2019-01-22 14:15
The issue is now fixed on the master branch.

**Closed as completed by ccarels** 2019-01-22 14:15 UTC
Labels: Documentation
